### PR TITLE
Result for workstation with Ryzen 9 - 5950x and 128GB @ 3600 MHz

### PR DESCRIPTION
**Pull request by frosteyes**
This workstation is also described at my website
http://www.frosteyes.dk/index.php/private/components-for-new-workstation
Please also see the attached lshw.txt for hardware information.

Notice it is a significant faster build for zeus compared to the currently logged Ryzen 5950x.
The current reference result is 3:17:45, where the result for this workstation is 2:37:29

Only the subfolder with results is part of this pull request, as I will leave the update of the csv files etc. to you

### CODE REVIEW

**Comment by shr-project** [comment]
Thanks, merged:
   ddf5b36..fef9482  results -> results

> Notice it is a significant faster build for zeus compared to the currently logged Ryzen 5950x.

yes, as it should be, I don't know if the 5950x from https://github.com/shr-project/test-oe-build-time/pull/7 was built primarily for OE (I hope not, because only 32G RAM, so it probably spent most of the extra time in swap with this kind of heavy OE build - but still might work relatively well when building "smaller" imaged without multiple webengines included :)). And he shared only the 4-build-all-cores results, which is the most unfavorable option for low memory builder.

> Only the subfolder with results is part of this pull request, as I will leave the update of the csv files etc. to you

Right, with your blog documenting the remaining details about the build it was easy to add the rest.

BTW: there is small typo in your blog post DDR4-3600 is PC-28800 (you were 800MB/s short with PC-28000).

Was tmpfs used for this build or not? Do you use tmpfs for performance or just to save writes to the NVMe? In my recent tests the performance isn't so different (compared to ext4 nobarrier commit=6000), but I still use it on some builders for CI builds (where the only interesting build artifact is the build log and an image and writing the rest to the disk would be a waste of write cycles or deleted from cache by the next build in queue before even being written), but then on 3970x it was showing interesting speedup, when I've used only 2 channels or lower 2666 speeds (see "individual-builds" sheet if interested). Would you be interested in sharing results with/without tmpfs (the faster individual-builds test would be enough to compare)?

**Comment by frosteyes** [comment]
Hi
Thanks for the quick update, and also for pointing the typo out in the blog post. Nice that some is reading it :)
I will to make an update with the result of the build and if it succeed based on my goal.

Please elaborate on in what capacity you mean tmpfs?
This build was just running the test directly to the NVMe, as I did not expect the complete result (poky) was able to fit inside 64 GB. Normally I have the sscache so I source to a "build" folder placed on tmpfs.
I would like to share more results if you like, just let me know what you would like to compare of the individual-builds?

**Comment by shr-project** [comment]
> Please elaborate on in what capacity you mean tmpfs?

OK, I see, in the blog post I've read:

> As I have a wish for using ramfs for all build outputs, I end up needing above 50G for the yocto build folder, combined with the memory needed for actually running the build processes.

So I wasn't sure if you were already using tmpfs/ramfs for this build as well.

> This build was just running the test directly to the NVMe, as I did not expect the complete result (poky) was able to fit inside 64 GB.

Thanks for confirming it was only on NVMe. 64GB might be too low, but I think 70-80GB with rm_work enabled would be enough (at least for 2 BB_NUMBER_THREADS), on VM-20t-98G-zeus it fit OK in tmpfs (with 80G max size), but with your 32threads it might leave less than optimal amount of ram for the threads actually doing the work.

> Normally I have the sscache so I source to a "build" folder placed on tmpfs.

sscache is sstate-cache? so you have sstate-cache + downloads on permanent NVMe drive and the TMPDIR completely on tmpfs? That's reasonable and what I do on CI builders (e.g. LuneOS builds on http://jenkins.nas-admin.org/), just keep in mind that nowadays with fast NVMe drives it's less about the performance and more about longevity of the SSDs at least based on my testing (with 8 core bulldozer FX-8120, 32G ram and slow HDDs couple years ago it was very different story with tmpfs).

So if you want to test how big impact (build-time wise) use of tmpfs has on your system, then I suggest to run
https://github.com/shr-project/test-oe-build-time/blob/hardknott/8-build-individual-components.mem.sh
and/or
https://github.com/shr-project/test-oe-build-time/blob/hardknott/8-build-individual-components.sh
you will probably need to adjust them a bit for your setup (and definitely would need to add build/tmp to your fstab), but because it doesn't build the whole image at the same time, then 60G tmpfs should be enough, with 128G ram on 3970x I was using:
```
none   /OE/build/test-oe-build-time/poky/build/tmp/    tmpfs   noatime,nodev,nosuid,size=60G,mode=1777,users,exec,uid=1000,gid=1000    0       0
```
and it was able to fit fine.

On my 3970x tmpfs isn't any faster now (compared with ext4 nobarrier,commit=6000 on fast gen4 NVMe drive), so I've stopped using tmpfs for the comfort of not using rm_work (faster incremental builds) and the possibility to leave multiple "in-progress" builds on disk instead of always struggling with multiple tmpfs mounts competing with still quite limited RAM. With the new 3995wx or Epyc and RDIMMs it might be different story, but the price is again quite a big higher than threadripper.

**Comment by frosteyes** [comment]
> > Normally I have the sscache so I source to a "build" folder placed on tmpfs.
> 
> sscache is sstate-cache? so you have sstate-cache + downloads on permanent NVMe drive and the TMPDIR completely on tmpfs? That's reasonable and what I do on CI builders (e.g. LuneOS builds on http://jenkins.nas-admin.org/), just keep in mind that nowadays with fast NVMe drives it's less about the performance and more about longevity of the SSDs at least based on my testing (with 8 core bulldozer FX-8120, 32G ram and slow HDDs couple years ago it was very different story with tmpfs).

Pretty much correct. I have a "shared" folder on at disk for all the downloads and sstate-cache outside the build structure.
E.g. something like _/path/to/disk/yocto/${VERSION}/downloads_ and  _/path/to/disk/yocto/${VERSION}/sstate_
Then I mount something like 32GB for a build folder and source the env into this. I completely agree that it is more about longevity of the SSD now, as the speed of a NVMe drive makes the performance difference it less visible. FYI, being a Gentoo user since 2004 means I also for many years have used something called temerge (just a shell wrapper on-top of emerge), using  tmpfs for compiling all the packages :)

> 
> So if you want to test how big impact (build-time wise) use of tmpfs has on your system, then I suggest to run
> https://github.com/shr-project/test-oe-build-time/blob/hardknott/8-build-individual-components.mem.sh
> and/or
> https://github.com/shr-project/test-oe-build-time/blob/hardknott/8-build-individual-components.sh
> you will probably need to adjust them a bit for your setup (and definitely would need to add build/tmp to your fstab), but because it doesn't build the whole image at the same time, then 60G tmpfs should be enough, with 128G ram on 3970x I was using:
> 
> ```
> none   /OE/build/test-oe-build-time/poky/build/tmp/    tmpfs   noatime,nodev,nosuid,size=60G,mode=1777,users,exec,uid=1000,gid=1000    0       0
> ```
> 
> and it was able to fit fine.
> 
> On my 3970x tmpfs isn't any faster now (compared with ext4 nobarrier,commit=6000 on fast gen4 NVMe drive), so I've stopped using tmpfs for the comfort of not using rm_work (faster incremental builds) and the possibility to leave multiple "in-progress" builds on disk instead of always struggling with multiple tmpfs mounts competing with still quite limited RAM. With the new 3995wx or Epyc and RDIMMs it might be different story, but the price is again quite a big higher than threadripper.

I have done a test where I compare a docker machine based on Ubuntu 18.04. One run using the normal nvme as storage and one with tmpfs.

build with nvme storage
`docker container run -t -i --rm --privileged --device /dev/net/tun:/dev/net/tun -h p1_yocto2020.3 -v /home/frosteyes/Desktop/oe-test/:/home/yocto/oe-test --name yocto yocto-ubuntu-18.04-dev`

build with 80G tmpfs as storage.
`docker container run -t -i --rm --privileged --device /dev/net/tun:/dev/net/tun -h p1_yocto2020.3 -v /home/frosteyes/Desktop/oe-test/:/home/yocto/oe-test --tmpfs /home/yocto/oe-test/test-oe-build-time/poky/build/tmp:rw,suid,dev,exec,size=80G --name yocto yocto-ubuntu-18.04-dev`

For both I run the 8-build-individual-components.sh on the zeus branch to test the difference.
I guess it is possible to optimize the root fs on the NVMe, but for now it tmpfs performance better.

Thanks for the help - I have attached the data below just for reference is anyone else is testing their system.
Currently I think the Ryzen 9 workstation gives an excellent performance versus price and quietness compared to its bigger brother in the ThreadRipper family.

NVMe build
frosteyes@nova ~/Desktop/oe-test/test-oe-build-time/nvme_build $ tail -n1 *.log
==> 8-build-individual-components.16.chromium-x11.log <==
TIME: 4024.90 0.87 9.13 0% 668 145466 9357 0 27896 0 bitbake -c compile chromium-x11

==> 8-build-individual-components.16.qtbase.log <==
TIME: 464.23 0.04 0.38 0% 9 13854 9370 0 27900 0 bitbake -c compile qtbase

==> 8-build-individual-components.16.qtdeclarative.log <==
TIME: 194.39 0.04 0.29 0% 6 11759 9366 0 27904 0 bitbake -c compile qtdeclarative

==> 8-build-individual-components.16.qtwebengine.log <==
TIME: 1346.32 0.30 3.44 0% 94 65844 9364 0 27764 0 bitbake -c compile qtwebengine

==> 8-build-individual-components.16.rust-native.log <==
TIME: 1124.71 0.04 0.41 0% 13 12639 9372 0 27984 0 bitbake -c compile rust-native

==> 8-build-individual-components.24.chromium-x11.log <==
TIME: 3587.78 0.86 9.71 0% 576 140699 9368 0 27816 0 bitbake -c compile chromium-x11

==> 8-build-individual-components.24.qtbase.log <==
TIME: 436.29 0.04 0.35 0% 8 12718 9363 0 27820 0 bitbake -c compile qtbase

==> 8-build-individual-components.24.qtdeclarative.log <==
TIME: 177.52 0.03 0.26 0% 8 12796 9356 0 27780 0 bitbake -c compile qtdeclarative

==> 8-build-individual-components.24.qtwebengine.log <==
TIME: 1162.39 0.36 3.43 0% 167 63144 9360 0 27572 0 bitbake -c compile qtwebengine

==> 8-build-individual-components.24.rust-native.log <==
TIME: 1131.57 0.02 0.42 0% 22 12886 9359 0 27840 0 bitbake -c compile rust-native

==> 8-build-individual-components.32.chromium-x11.log <==
TIME: 3420.56 0.87 10.12 0% 753 105969 9363 0 27836 0 bitbake -c compile chromium-x11

==> 8-build-individual-components.32.qtbase.log <==
TIME: 423.59 0.03 0.34 0% 25 13780 9364 0 27960 0 bitbake -c compile qtbase

==> 8-build-individual-components.32.qtdeclarative.log <==
TIME: 168.77 0.02 0.26 0% 5 12794 9362 0 27952 0 bitbake -c compile qtdeclarative

==> 8-build-individual-components.32.qtwebengine.log <==
TIME: 1155.13 0.31 3.46 0% 572 49766 9357 0 27996 0 bitbake -c compile qtwebengine

==> 8-build-individual-components.32.rust-native.log <==
TIME: 1162.33 0.02 0.44 0% 7 13010 9364 0 27908 0 bitbake -c compile rust-native

Tmpfs build
frosteyes@nova ~/Desktop/oe-test/test-oe-build-time/tmpfs_build $ tail -n1 *.log
==> 8-build-individual-components.16.chromium-x11.log <==
TIME: 3547.38 0.78 8.22 0% 647 142400 9360 0 27916 0 bitbake -c compile chromium-x11

==> 8-build-individual-components.16.qtbase.log <==
TIME: 398.66 0.04 0.31 0% 11 13607 9361 0 27928 0 bitbake -c compile qtbase

==> 8-build-individual-components.16.qtdeclarative.log <==
TIME: 172.34 0.03 0.27 0% 7 11722 9368 0 28012 0 bitbake -c compile qtdeclarative

==> 8-build-individual-components.16.qtwebengine.log <==
TIME: 1147.18 0.28 2.89 0% 129 63792 9367 0 27900 0 bitbake -c compile qtwebengine

==> 8-build-individual-components.16.rust-native.log <==
TIME: 1030.84 0.02 0.35 0% 26 12240 9357 0 27924 0 bitbake -c compile rust-native

==> 8-build-individual-components.24.chromium-x11.log <==
TIME: 3310.44 0.76 8.89 0% 287 141542 9356 0 27896 0 bitbake -c compile chromium-x11

==> 8-build-individual-components.24.qtbase.log <==
TIME: 398.73 0.03 0.32 0% 11 12543 9362 0 28008 0 bitbake -c compile qtbase

==> 8-build-individual-components.24.qtdeclarative.log <==
TIME: 163.57 0.02 0.27 0% 7 12733 9363 0 27936 0 bitbake -c compile qtdeclarative

==> 8-build-individual-components.24.qtwebengine.log <==
TIME: 1059.22 0.28 3.09 0% 119 64538 9370 0 28072 0 bitbake -c compile qtwebengine

==> 8-build-individual-components.24.rust-native.log <==
TIME: 1034.00 0.04 0.33 0% 24 12422 9358 0 27932 0 bitbake -c compile rust-native

==> 8-build-individual-components.32.chromium-x11.log <==
TIME: 3120.27 0.68 8.65 0% 631 102861 9365 0 27976 0 bitbake -c compile chromium-x11

==> 8-build-individual-components.32.qtbase.log <==
TIME: 401.87 0.04 0.33 0% 11 13678 9369 0 27988 0 bitbake -c compile qtbase

==> 8-build-individual-components.32.qtdeclarative.log <==
TIME: 161.31 0.02 0.25 0% 13 11387 9369 0 28024 0 bitbake -c compile qtdeclarative

==> 8-build-individual-components.32.qtwebengine.log <==
TIME: 997.65 0.27 2.97 0% 272 50006 9367 0 28016 0 bitbake -c compile qtwebengine

==> 8-build-individual-components.32.rust-native.log <==
TIME: 1027.47 0.02 0.34 0% 20 12463 9354 0 28008 0 bitbake -c compile rust-native

**Comment by shr-project** [comment]
Can you please submit PR with these 8-build-individual-components.*.log files? It would be much easier for me to add them to the .csv and tables, if you still have them.

**Comment by frosteyes** [comment]
See https://github.com/shr-project/test-oe-build-time/pull/9 for results files.

**Pull request closed without merging**
